package Core;

/****************************************************
 * 
 * FIX URL VALIDATION AND ADD RED COLOR TEXTBOX WHEN ERROR
 * DO PRIORITY for REMINDERS
 * 
 ******************************************************/
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahlin
 */
public class addLink extends javax.swing.JFrame {

    /**
     * Creates new form addLink
     */
    public addLink() {
        initComponents();
        setLocationRelativeTo(null);
        
        linkNameError.setVisible(false);
        linkError.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        link_name = new javax.swing.JTextField();
        cancelBtn = new javax.swing.JButton();
        saveBtn = new javax.swing.JButton();
        link = new javax.swing.JTextField();
        linkNameError = new javax.swing.JLabel();
        linkError = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(550, 340));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(null);

        link_name.setBackground(new java.awt.Color(243, 240, 231));
        link_name.setBorder(null);
        getContentPane().add(link_name);
        link_name.setBounds(215, 92, 284, 30);

        cancelBtn.setBorder(null);
        cancelBtn.setBorderPainted(false);
        cancelBtn.setContentAreaFilled(false);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(cancelBtn);
        cancelBtn.setBounds(326, 257, 135, 39);

        saveBtn.setBorder(null);
        saveBtn.setBorderPainted(false);
        saveBtn.setContentAreaFilled(false);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(saveBtn);
        saveBtn.setBounds(112, 257, 135, 39);

        link.setBackground(new java.awt.Color(243, 240, 231));
        link.setBorder(null);
        getContentPane().add(link);
        link.setBounds(221, 171, 276, 30);

        linkNameError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/addLinkNameError.png"))); // NOI18N
        getContentPane().add(linkNameError);
        linkNameError.setBounds(209, 86, 294, 40);

        linkError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/addLinkError.png"))); // NOI18N
        getContentPane().add(linkError);
        linkError.setBounds(119, 165, 390, 40);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/addLink.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(450, 300));
        background.setMinimumSize(new java.awt.Dimension(450, 300));
        background.setPreferredSize(new java.awt.Dimension(450, 300));
        getContentPane().add(background);
        background.setBounds(0, 0, 550, 340);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        // TODO add your handling code here:
        quicklinksHelper user = new quicklinksHelper();
        Validation validate = new Validation();
        Util utility = new Util();
        
        boolean error = false;
        
        String linknames = link_name.getText().trim();
        String link_input = link.getText().trim();
        
        int httpPos = utility.findStringOccurrence(link_input, "http://");
        int httpsPos = utility.findStringOccurrence(link_input, "https://");
        int wwwPos = utility.findStringOccurrence(link_input, "www.");
        
        if(httpPos == -1 && httpsPos == -1){
            //Doesn't exist in the user input
            if(wwwPos == -1){
                link_input = "http://www." + link_input;
            } else {
                link_input = "http://" + link_input;
            }
        }
        
        if(validate.validateTextLength(linknames, 15, "Web Name") == false || validate.stringIsEmpty(linknames) == true){
            error = true;
            linkNameError.setVisible(true);
            linkError.setVisible(false);
        }
        
        if(validate.validateURL(link_input) == false){
            error = true;
            linkNameError.setVisible(false);
            linkError.setVisible(true);
        }
        
        if(validate.stringIsEmpty(link_input.substring(11)) == true){
            error = true;
            linkNameError.setVisible(false);
            linkError.setVisible(true);
        }
        
        if(error == false) {
            if(user.insertLink(linknames,link_input)){
                linkNameError.setVisible(true);
                linkError.setVisible(true);
                
                QuickLinks window = new QuickLinks();
                this.setVisible(false);
                window.setVisible(true);
            }
       }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        // TODO add your handling code here:
        QuickLinks window = new QuickLinks();
        
        this.setVisible(false);
        window.setVisible(true);
    }//GEN-LAST:event_cancelBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addLink.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addLink().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JTextField link;
    private javax.swing.JLabel linkError;
    private javax.swing.JLabel linkNameError;
    private javax.swing.JTextField link_name;
    private javax.swing.JButton saveBtn;
    // End of variables declaration//GEN-END:variables
}
