package Core;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author sarah
 */
public class addNote extends javax.swing.JFrame {

    /**
     * Creates new form AddNote
     */
    public addNote() {
        initComponents();
        setLocationRelativeTo(this);
        this.setResizable(false);
        
        errorTitleLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        NoteTitle = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        NoteBody = new javax.swing.JTextArea();
        Save_btn = new javax.swing.JButton();
        Discard_btn = new javax.swing.JButton();
        errorTitleLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 400));
        setUndecorated(true);
        getContentPane().setLayout(null);

        NoteTitle.setBackground(new java.awt.Color(243, 240, 231));
        NoteTitle.setBorder(null);
        NoteTitle.setOpaque(false);
        NoteTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NoteTitleActionPerformed(evt);
            }
        });
        getContentPane().add(NoteTitle);
        NoteTitle.setBounds(209, 109, 330, 30);

        jScrollPane1.setBorder(null);

        NoteBody.setBackground(new java.awt.Color(243, 240, 231));
        NoteBody.setColumns(20);
        NoteBody.setLineWrap(true);
        NoteBody.setRows(5);
        NoteBody.setBorder(null);
        NoteBody.setOpaque(false);
        jScrollPane1.setViewportView(NoteBody);
        jScrollPane1.setViewportBorder(null);
        jScrollPane1.setBorder(null);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(210, 170, 330, 100);

        Save_btn.setBorder(null);
        Save_btn.setBorderPainted(false);
        Save_btn.setContentAreaFilled(false);
        Save_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Save_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Save_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Save_btn);
        Save_btn.setBounds(129, 322, 142, 43);

        Discard_btn.setBorder(null);
        Discard_btn.setBorderPainted(false);
        Discard_btn.setContentAreaFilled(false);
        Discard_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Discard_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Discard_btnActionPerformed(evt);
            }
        });
        getContentPane().add(Discard_btn);
        Discard_btn.setBounds(354, 322, 142, 43);

        errorTitleLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/errorTextbox1.jpg"))); // NOI18N
        getContentPane().add(errorTitleLabel);
        errorTitleLabel.setBounds(205, 105, 347, 38);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/addNote.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 625, 400);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void NoteTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NoteTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NoteTitleActionPerformed

    private void Save_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Save_btnActionPerformed
        // TODO add your handling code here:
        notesHelper user = new notesHelper();
        boolean error = false;
        
        String title = NoteTitle.getText();
        String body = NoteBody.getText();
        
        Validation validate = new Validation();
        
        if(validate.validateTextLength(title, 20, "Title") == false) {
            error = true;
        }
        
        if(validate.stringIsEmpty(title) == true){
            error = true;
        }
        
        if(error == false) {
            if(user.insertNote(title,body)){
                errorTitleLabel.setVisible(true);
                
                Notes next = new Notes();
                next.setVisible(true);
                
                this.setVisible(false);
                dispose();
            }
       } else {
            errorTitleLabel.setVisible(true);
       }
    }//GEN-LAST:event_Save_btnActionPerformed

    private void Discard_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Discard_btnActionPerformed
        Notes window = new Notes();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_Discard_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addNote.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addNote().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Discard_btn;
    private javax.swing.JTextArea NoteBody;
    private javax.swing.JTextField NoteTitle;
    private javax.swing.JButton Save_btn;
    private javax.swing.JLabel background;
    private javax.swing.JLabel errorTitleLabel;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
