package Core;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahlin
 */
public class addRecord extends javax.swing.JFrame {

    /**
     * Creates new form addExpense
     */
    public addRecord() {
        initComponents();
        setLocationRelativeTo(this);
        incomeRadioCircle.setVisible(false);
        
        errorAmountLabel.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        type = new javax.swing.ButtonGroup();
        noteInput = new javax.swing.JTextField();
        amountInput = new javax.swing.JTextField();
        categoryInput = new javax.swing.JComboBox<>();
        CancelButtonLabel = new javax.swing.JLabel();
        SaveButtonLabel = new javax.swing.JLabel();
        expenseRadioCircle = new javax.swing.JLabel();
        incomeRadioCircle = new javax.swing.JLabel();
        errorAmountLabel = new javax.swing.JLabel();
        background = new javax.swing.JLabel();
        expenseRadio = new javax.swing.JRadioButton();
        incomeRadio = new javax.swing.JRadioButton();
        SaveButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(625, 500));
        setUndecorated(true);
        getContentPane().setLayout(null);

        noteInput.setBackground(new java.awt.Color(243, 240, 231));
        noteInput.setBorder(null);
        noteInput.setOpaque(false);
        getContentPane().add(noteInput);
        noteInput.setBounds(172, 100, 335, 30);

        amountInput.setBackground(new java.awt.Color(243, 240, 231));
        amountInput.setBorder(null);
        amountInput.setOpaque(false);
        getContentPane().add(amountInput);
        amountInput.setBounds(220, 240, 286, 27);

        categoryInput.setBackground(new java.awt.Color(243, 240, 231));
        categoryInput.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Food & Drinks", "Transportation", "Life & Entertainment", "Salary", "Tax", "Child Support", "Phone", "Education", "Commission", "Others" }));
        categoryInput.setBorder(null);
        categoryInput.setFocusable(false);
        categoryInput.setOpaque(false);
        getContentPane().add(categoryInput);
        categoryInput.setBounds(164, 304, 350, 40);

        CancelButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(CancelButtonLabel);
        CancelButtonLabel.setBounds(355, 417, 160, 47);

        SaveButtonLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(SaveButtonLabel);
        SaveButtonLabel.setBounds(102, 417, 160, 47);

        expenseRadioCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/RadioSelectedCircle.png"))); // NOI18N
        getContentPane().add(expenseRadioCircle);
        expenseRadioCircle.setBounds(174, 178, 10, 10);

        incomeRadioCircle.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/RadioSelectedCircle.png"))); // NOI18N
        getContentPane().add(incomeRadioCircle);
        incomeRadioCircle.setBounds(341, 178, 10, 10);

        errorAmountLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/errorTextbox.jpg"))); // NOI18N
        getContentPane().add(errorAmountLabel);
        errorAmountLabel.setBounds(166, 234, 347, 38);

        background.setBackground(new java.awt.Color(243, 240, 231));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/addRecord.jpg"))); // NOI18N
        background.setOpaque(true);
        getContentPane().add(background);
        background.setBounds(0, 0, 625, 500);

        type.add(expenseRadio);
        expenseRadio.setSelected(true);
        expenseRadio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        expenseRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                expenseRadioMouseClicked(evt);
            }
        });
        getContentPane().add(expenseRadio);
        expenseRadio.setBounds(170, 170, 110, 30);

        type.add(incomeRadio);
        incomeRadio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        incomeRadio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                incomeRadioMouseClicked(evt);
            }
        });
        getContentPane().add(incomeRadio);
        incomeRadio.setBounds(333, 170, 100, 30);

        SaveButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SaveButton.setOpaque(false);
        SaveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveButtonActionPerformed(evt);
            }
        });
        getContentPane().add(SaveButton);
        SaveButton.setBounds(102, 417, 160, 47);

        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        getContentPane().add(CancelButton);
        CancelButton.setBounds(355, 417, 160, 47);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void expenseRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_expenseRadioMouseClicked
        // TODO add your handling code here:
        expenseRadioCircle.setVisible(true);
        incomeRadioCircle.setVisible(false);
    }//GEN-LAST:event_expenseRadioMouseClicked

    private void incomeRadioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_incomeRadioMouseClicked
        // TODO add your handling code here:
        expenseRadioCircle.setVisible(false);
        incomeRadioCircle.setVisible(true);
    }//GEN-LAST:event_incomeRadioMouseClicked

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        // TODO add your handling code here:
        Wallet window = new Wallet();
        window.setVisible(true);
        this.setVisible(false);
        //Close the frame completely
        dispose();
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void SaveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveButtonActionPerformed
        // TODO add your handling code here:
        String note = noteInput.getText();
        String category = (String) categoryInput.getSelectedItem();
        
        boolean error = false;
           
        short type = 0;
        
        if(expenseRadio.isSelected()){
            type = 0;
        } else if(incomeRadio.isSelected()){
            type = 1;
        }
        
        double amount = 0;
        
        try {
            amount = Double.parseDouble(amountInput.getText());
            
            if(amount < 1){
                error = true;
                errorAmountLabel.setVisible(true);
            }
                    
        } catch(NumberFormatException e){
            errorAmountLabel.setVisible(true);
            error = true;
        }
        
        if(error == false){
            walletHelper helper = new walletHelper();
            helper.insertRecord(note, type, amount, category);
            
            Wallet window = new Wallet();
            window.setVisible(true);
            this.setVisible(false);
            dispose();
        }
    }//GEN-LAST:event_SaveButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addRecord.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addRecord().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel CancelButtonLabel;
    private javax.swing.JButton SaveButton;
    private javax.swing.JLabel SaveButtonLabel;
    private javax.swing.JTextField amountInput;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> categoryInput;
    private javax.swing.JLabel errorAmountLabel;
    private javax.swing.JRadioButton expenseRadio;
    private javax.swing.JLabel expenseRadioCircle;
    private javax.swing.JRadioButton incomeRadio;
    private javax.swing.JLabel incomeRadioCircle;
    private javax.swing.JTextField noteInput;
    private javax.swing.ButtonGroup type;
    // End of variables declaration//GEN-END:variables
}
