package Core;

import java.io.IOException;
import java.net.URI;
import javax.swing.BorderFactory;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahlin
 */
public class ForgotPassword extends javax.swing.JFrame {

    /**
     * Creates new form ForgotPassword
     */
    public ForgotPassword() {
        initComponents();
        setLocationRelativeTo(this);
        this.setResizable(false); 
        
        errorIco.setVisible(false);
        error_message.setVisible(false);
        signupMsg.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        signupMsg = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        message2 = new javax.swing.JLabel();
        email_input = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        message1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        error_message = new javax.swing.JLabel();
        errorIco = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(901, 569));
        getContentPane().setLayout(null);

        signupMsg.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signupMsg.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signupMsgMouseClicked(evt);
            }
        });
        getContentPane().add(signupMsg);
        signupMsg.setBounds(560, 330, 50, 10);

        jLabel1.setFont(new java.awt.Font("Open Sans Light", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(59, 59, 59));
        jLabel1.setText("Forgot Password?");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(300, 100, 320, 50);

        message2.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
        message2.setForeground(new java.awt.Color(59, 59, 59));
        message2.setText("Upon submission, you will be redirected to your email.");
        getContentPane().add(message2);
        message2.setBounds(290, 340, 380, 20);

        email_input.setBackground(new java.awt.Color(243, 240, 231));
        email_input.setToolTipText("");
        email_input.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 51, 51), 2, true));
        email_input.setBorder(BorderFactory.createCompoundBorder(
            email_input.getBorder(),
            BorderFactory.createEmptyBorder(5, 5, 5, 5)));
    email_input.setOpaque(false);
    getContentPane().add(email_input);
    email_input.setBounds(320, 240, 270, 50);

    jLabel3.setFont(new java.awt.Font("Open Sans", 0, 18)); // NOI18N
    jLabel3.setForeground(new java.awt.Color(59, 59, 59));
    jLabel3.setText("Enter your e-mail address");
    getContentPane().add(jLabel3);
    jLabel3.setBounds(350, 180, 220, 50);

    message1.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
    message1.setForeground(new java.awt.Color(59, 59, 59));
    message1.setText("Your password will be sent to your e-mail account. ");
    getContentPane().add(message1);
    message1.setBounds(300, 310, 350, 20);

    jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/forgotPassSubmitBtn.jpg"))); // NOI18N
    jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    getContentPane().add(jLabel2);
    jLabel2.setBounds(320, 390, 270, 40);

    jButton1.setBackground(new java.awt.Color(0, 135, 95));
    jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
    jButton1.setForeground(new java.awt.Color(255, 255, 255));
    jButton1.setBorder(null);
    jButton1.setBorderPainted(false);
    jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jButton1.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            jButton1ActionPerformed(evt);
        }
    });
    getContentPane().add(jButton1);
    jButton1.setBounds(320, 390, 270, 40);

    jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/web-home-flat-sign-by-Vexels.png"))); // NOI18N
    jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel5MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel5);
    jLabel5.setBounds(820, 0, 50, 70);

    jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    jLabel6.setForeground(new java.awt.Color(59, 59, 59));
    jLabel6.setText("Back to Home");
    jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            jLabel6MouseClicked(evt);
        }
    });
    getContentPane().add(jLabel6);
    jLabel6.setBounds(720, 10, 100, 50);

    error_message.setFont(new java.awt.Font("Open Sans", 0, 14)); // NOI18N
    error_message.setForeground(new java.awt.Color(59, 59, 59));
    error_message.setText("You aren't registered with us yet! Sign up?");
    getContentPane().add(error_message);
    error_message.setBounds(350, 310, 320, 50);

    errorIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
    getContentPane().add(errorIco);
    errorIco.setBounds(290, 300, 60, 70);

    background.setBackground(new java.awt.Color(243, 240, 231));
    background.setOpaque(true);
    getContentPane().add(background);
    background.setBounds(0, 0, 901, 569);

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Validation validate = new Validation();
        usersHelper user = new usersHelper();
        
        String email = email_input.getText();
        String errorMessage = "";
        
        if(validate.validateEmail(email)){
            //Valid email provided

            //Check if the email exists in the db
            if(user.checkEmail(email)){
                try {
                   //Email exists
                   int user_id = user.getIdbyEmail(email);
                   StringBuilder password = new StringBuilder(user.getPassword(user_id));

                   String username = user.getUsername(user_id);

                   //Insert garbage values to the password to encrypt it - Simple way
                   password.insert(4, "ⱣⱤⱪⱩḁḩḭṉẄẂṖẍẔẚἾỶẪỈỦἎἆỡ");
                   password.insert(1, "ⱣⱤⱪⱩḁḩἾỶẪỈỦἎἆỡ");

                   //Open the webpage and redirect users to their email
                   java.awt.Desktop.getDesktop().browse(URI.create("http://shell.testnow.altervista.org/shell/forgotPass.php?email=" + email + "&username=" + username + "&password=ⱣⱤⱪⱩḁḩḭṉẄẂṖẍẔẚἾỶẪỈỦἎἆỡ" + password + "ⱣⱤⱪⱩḁḩḭṉẄẂṖẍẔẚἾỶẪỈỦἎἆỡ"));
                } catch (IOException ex) {
                   System.out.println(ex);
                }
            } else {
               //Email does not exist in the table
               signupMsg.setVisible(true);
               errorMessage = "You aren't registered with us yet! Sign up?";
               
               //Existing messages
               message1.setVisible(false);
               message2.setVisible(false);
               
               errorIco.setVisible(true);
               error_message.setVisible(true);
               error_message.setText(errorMessage);
            }
        } else {
            errorMessage = validate.error;
            
            
            message1.setVisible(false);
            message2.setVisible(false);

            errorIco.setVisible(true);
            error_message.setVisible(true);
            error_message.setText(errorMessage);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Login next = new Login();
        next.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        Login next = new Login();
        next.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void signupMsgMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signupMsgMouseClicked
        // TODO add your handling code here:
        Login next = new Login();
        next.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_signupMsgMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgotPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForgotPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JTextField email_input;
    private javax.swing.JLabel errorIco;
    private javax.swing.JLabel error_message;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel message1;
    private javax.swing.JLabel message2;
    private javax.swing.JLabel signupMsg;
    // End of variables declaration//GEN-END:variables
}
