package Core;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahlin
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Test
     */
    public Login() {
        
        try {
            Thread.sleep(1500);
        } catch(Exception e){}
        
        initComponents();
        setLocationRelativeTo(null);
        
        this.setResizable(false); 
        
        loginFailed.setVisible(false);
        errorIco.setVisible(false);
        
        signupSuccess.setVisible(false);
        signupSuccessIco.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        logo = new javax.swing.JLabel();
        login_username = new javax.swing.JTextField();
        login_password = new javax.swing.JPasswordField();
        signin_btn = new javax.swing.JButton();
        signup_username = new javax.swing.JTextField();
        signup_email = new javax.swing.JTextField();
        signup_password = new javax.swing.JPasswordField();
        signup_btn = new javax.swing.JButton();
        forgotPassword = new javax.swing.JButton();
        loginFailed = new javax.swing.JLabel();
        signupSuccessIco = new javax.swing.JLabel();
        errorIco = new javax.swing.JLabel();
        signupSuccess = new javax.swing.JLabel();
        signupError = new javax.swing.JLabel();
        aboutUsLabel = new javax.swing.JLabel();
        contactUsBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(900, 600));
        getContentPane().setLayout(null);

        logo.setFont(new java.awt.Font("Colors Of Autumn", 0, 36)); // NOI18N
        logo.setForeground(new java.awt.Color(74, 72, 65));
        logo.setText("SHELL");
        getContentPane().add(logo);
        logo.setBounds(50, 0, 220, 100);

        login_username.setBackground(new java.awt.Color(243, 240, 231));
        login_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_username.setForeground(new java.awt.Color(102, 102, 102));
        login_username.setText("Username");
        login_username.setBorder(null);
        login_username.setNextFocusableComponent(login_password);
        login_username.setOpaque(false);
        login_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_usernameFocusLost(evt);
            }
        });
        login_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_usernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                login_usernameMouseExited(evt);
            }
        });
        getContentPane().add(login_username);
        login_username.setBounds(140, 220, 220, 40);

        login_password.setBackground(new java.awt.Color(243, 240, 231));
        login_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        login_password.setForeground(new java.awt.Color(102, 102, 102));
        login_password.setText("password");
        login_password.setBorder(null);
        login_password.setEchoChar('●');
        login_password.setNextFocusableComponent(signin_btn);
        login_password.setOpaque(false);
        login_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                login_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                login_passwordFocusLost(evt);
            }
        });
        login_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                login_passwordMouseClicked(evt);
            }
        });
        getContentPane().add(login_password);
        login_password.setBounds(140, 280, 220, 40);

        signin_btn.setContentAreaFilled(false);
        signin_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signin_btn.setNextFocusableComponent(forgotPassword);
        signin_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signin_btnActionPerformed(evt);
            }
        });
        getContentPane().add(signin_btn);
        signin_btn.setBounds(133, 360, 230, 40);

        signup_username.setBackground(new java.awt.Color(243, 240, 231));
        signup_username.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_username.setForeground(new java.awt.Color(102, 102, 102));
        signup_username.setText("Username");
        signup_username.setToolTipText("");
        signup_username.setBorder(null);
        signup_username.setNextFocusableComponent(signup_email);
        signup_username.setOpaque(false);
        signup_username.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                signup_usernameCaretUpdate(evt);
            }
        });
        signup_username.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_usernameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_usernameFocusLost(evt);
            }
        });
        signup_username.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_usernameMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                signup_usernameMouseExited(evt);
            }
        });
        signup_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_usernameActionPerformed(evt);
            }
        });
        getContentPane().add(signup_username);
        signup_username.setBounds(550, 223, 225, 37);

        signup_email.setBackground(new java.awt.Color(243, 240, 231));
        signup_email.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_email.setForeground(new java.awt.Color(102, 102, 102));
        signup_email.setText("Email ID");
        signup_email.setToolTipText("");
        signup_email.setBorder(null);
        signup_email.setNextFocusableComponent(signup_password);
        signup_email.setOpaque(false);
        signup_email.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_emailFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_emailFocusLost(evt);
            }
        });
        signup_email.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_emailMouseClicked(evt);
            }
        });
        signup_email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_emailActionPerformed(evt);
            }
        });
        getContentPane().add(signup_email);
        signup_email.setBounds(550, 282, 220, 39);

        signup_password.setBackground(new java.awt.Color(243, 240, 231));
        signup_password.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        signup_password.setForeground(new java.awt.Color(102, 102, 102));
        signup_password.setText("password");
        signup_password.setToolTipText("Password must be greater than 6 characters");
        signup_password.setBorder(null);
        signup_password.setEchoChar('●');
        signup_password.setNextFocusableComponent(signup_btn);
        signup_password.setOpaque(false);
        signup_password.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                signup_passwordFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                signup_passwordFocusLost(evt);
            }
        });
        signup_password.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                signup_passwordMouseClicked(evt);
            }
        });
        signup_password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_passwordActionPerformed(evt);
            }
        });
        getContentPane().add(signup_password);
        signup_password.setBounds(550, 342, 220, 40);

        signup_btn.setContentAreaFilled(false);
        signup_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        signup_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signup_btnActionPerformed(evt);
            }
        });
        getContentPane().add(signup_btn);
        signup_btn.setBounds(550, 420, 230, 30);

        forgotPassword.setContentAreaFilled(false);
        forgotPassword.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        forgotPassword.setNextFocusableComponent(signup_username);
        forgotPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forgotPasswordActionPerformed(evt);
            }
        });
        getContentPane().add(forgotPassword);
        forgotPassword.setBounds(160, 423, 180, 30);

        loginFailed.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        loginFailed.setForeground(new java.awt.Color(59, 59, 59));
        loginFailed.setText("Incorrect username or password. Try again!");
        getContentPane().add(loginFailed);
        loginFailed.setBounds(280, 500, 410, 40);

        signupSuccessIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/success.png"))); // NOI18N
        getContentPane().add(signupSuccessIco);
        signupSuccessIco.setBounds(260, 490, 50, 64);

        errorIco.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/close.png"))); // NOI18N
        getContentPane().add(errorIco);
        errorIco.setBounds(220, 490, 50, 64);

        signupSuccess.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signupSuccess.setForeground(new java.awt.Color(59, 59, 59));
        signupSuccess.setText("Account successfully created!");
        getContentPane().add(signupSuccess);
        signupSuccess.setBounds(330, 510, 350, 20);

        signupError.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        signupError.setForeground(new java.awt.Color(59, 59, 59));
        getContentPane().add(signupError);
        signupError.setBounds(280, 510, 550, 20);

        aboutUsLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        aboutUsLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                aboutUsLabelMouseClicked(evt);
            }
        });
        getContentPane().add(aboutUsLabel);
        aboutUsLabel.setBounds(590, 20, 70, 40);

        contactUsBtn.setBorder(null);
        contactUsBtn.setBorderPainted(false);
        contactUsBtn.setContentAreaFilled(false);
        contactUsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        contactUsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                contactUsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                contactUsBtnMouseExited(evt);
            }
        });
        contactUsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contactUsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(contactUsBtn);
        contactUsBtn.setBounds(700, 20, 120, 40);

        background.setForeground(new java.awt.Color(102, 102, 102));
        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Login.jpg"))); // NOI18N
        background.setMaximumSize(new java.awt.Dimension(1000, 1000));
        getContentPane().add(background);
        background.setBounds(0, 0, 900, 570);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void signup_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_btnActionPerformed
        // TODO add your handling code here:
        
        //Clear previous labels
        loginFailed.setVisible(false);
        errorIco.setVisible(false);
        
        usersHelper users = new usersHelper();
        Validation validate = new Validation();
        
        String username = signup_username.getText();
        String password = new String(signup_password.getPassword());
        String email    = signup_email.getText();
        
        boolean error = false;
        String errorMessage = "";
        
        if(validate.validatePassword(password) == false){
            //Invalid password
            errorMessage = validate.error;
            error = true;
        }
        
        if(validate.validateEmail(email) == false){
            //Invalid email
            errorMessage = validate.error;
            error = true;
        }
        
        if(users.checkEmail(email) == true){
            //Email already exists
            errorMessage = "The email is associated with another username";
            error = true;
        }
        
        if(users.checkUsername(username) == true){
            //Username found
            errorMessage = "Username already exists. Try again!";
            error = true;
        }
        
        if(validate.validateUsername(username) == false){
            //Invalid username
            errorMessage = validate.error;
            error = true;
        }
        
        //Valid input - Insert user
        if(error == false){
            //Successfully inserted user
            if(users.insertUser(username, password, email)){
                Home window = new Home();
                
                Home.firstTimeCheck.setText("firsttime");
                
                this.setVisible(false);
                window.setVisible(true);
                
                /*errorIco.setVisible(false);
                loginFailed.setVisible(false);
                signupError.setVisible(false);
                
                signupSuccessIco.setVisible(true);
                signupSuccess.setVisible(true);*/
                
            }
        } else {
            //Signup failed
            errorIco.setVisible(true);
            signupError.setText(errorMessage);
        }
    }//GEN-LAST:event_signup_btnActionPerformed

    private void signin_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signin_btnActionPerformed
        // TODO add your handling code here:
        
        //Clear previous labels
        signupSuccess.setVisible(false);
        signupSuccessIco.setVisible(false);
        
        usersHelper users = new usersHelper();
        String username = login_username.getText();
        String password = new String(login_password.getPassword());
        
        if(users.checkLogin(username, password)){
            //Correct credentials entered
            
            users.setLoggedIn(username);
            
            //Redirect user to home
            Home next = new Home();
            
            next.setVisible(true);
            this.setVisible(false);
        } else {
            errorIco.setVisible(true);
            loginFailed.setVisible(true);
        }
        
    }//GEN-LAST:event_signin_btnActionPerformed

    private void login_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_usernameFocusGained
        // TODO add your handling code here:
        String username = login_username.getText();
        
        if(username.equals("Username")){
            login_username.setText("");
        }
    }//GEN-LAST:event_login_usernameFocusGained

    private void login_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_usernameMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_login_usernameMouseClicked

    private void login_usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_usernameMouseExited
        // TODO add your handling code here:
        
    }//GEN-LAST:event_login_usernameMouseExited

    private void login_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_usernameFocusLost
        // TODO add your handling code here:
        String username = login_username.getText();
        
        if(username.equals("")){
            //Default username
            login_username.setText("Username");
        }
    }//GEN-LAST:event_login_usernameFocusLost

    private void login_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_login_passwordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_login_passwordMouseClicked

    private void login_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passwordFocusLost
        // TODO add your handling code here:
        String password = new String(login_password.getPassword());
        
        if(password.equals("")){
            login_password.setText("password");
        }
    }//GEN-LAST:event_login_passwordFocusLost

    private void signup_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_usernameActionPerformed

    private void signup_usernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_usernameMouseClicked
        // TODO add your handling code here:    
    }//GEN-LAST:event_signup_usernameMouseClicked

    private void signup_emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_emailActionPerformed

    private void signup_emailMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_emailMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_emailMouseClicked

    private void signup_usernameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_usernameFocusLost
        // TODO add your handling code here:
        String username = signup_username.getText();
        
        if(username.equals("")){
            //Default username
            signup_username.setText("Username");
        }
    }//GEN-LAST:event_signup_usernameFocusLost

    private void signup_emailFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_emailFocusLost
        // TODO add your handling code here:
        String email = signup_email.getText();
        
        if(email.equals("")){
            signup_email.setText("Email ID");
        }
    }//GEN-LAST:event_signup_emailFocusLost

    private void signup_passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signup_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_passwordActionPerformed

    private void signup_passwordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_passwordMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_signup_passwordMouseClicked

    private void signup_passwordFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusLost
        // TODO add your handling code here:
        String password = new String(signup_password.getPassword());
        
        if(password.equals("")){
            signup_password.setText("password");
        }
    }//GEN-LAST:event_signup_passwordFocusLost

    private void signup_usernameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_usernameFocusGained
        // TODO add your handling code here:
        String username = signup_username.getText();
        
        if(username.equals("Username")){
            signup_username.setText("");
        }
    }//GEN-LAST:event_signup_usernameFocusGained

    private void login_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_login_passwordFocusGained
        // TODO add your handling code here:
        String password = new String(login_password.getPassword());
        
        if(password.equals("password")){
            login_password.setText("");
        }
    }//GEN-LAST:event_login_passwordFocusGained

    private void signup_emailFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_emailFocusGained
        // TODO add your handling code here:
        String email = signup_email.getText();
        
        if(email.equals("Email ID")){
            signup_email.setText("");
        }
    }//GEN-LAST:event_signup_emailFocusGained

    private void signup_passwordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_signup_passwordFocusGained
        // TODO add your handling code here:
        String password = new String(signup_password.getPassword());
        
        if(password.equals("password")){
            signup_password.setText("");
        }
    }//GEN-LAST:event_signup_passwordFocusGained

    private void signup_usernameCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_signup_usernameCaretUpdate
        // TODO add your handling code here:
    }//GEN-LAST:event_signup_usernameCaretUpdate

    private void signup_usernameMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_signup_usernameMouseExited

    }//GEN-LAST:event_signup_usernameMouseExited

    private void forgotPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forgotPasswordActionPerformed
        // TODO add your handling code here:
        ForgotPassword next = new ForgotPassword();
        next.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_forgotPasswordActionPerformed

    private void aboutUsLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_aboutUsLabelMouseClicked
        // TODO add your handling code here:
        AboutUs window = new AboutUs();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_aboutUsLabelMouseClicked

    private void contactUsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUsBtnMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_contactUsBtnMouseEntered

    private void contactUsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_contactUsBtnMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_contactUsBtnMouseExited

    private void contactUsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contactUsBtnActionPerformed
        // TODO add your handling code here:
        ContactUs window = new ContactUs();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_contactUsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel aboutUsLabel;
    private javax.swing.JLabel background;
    private javax.swing.JButton contactUsBtn;
    private javax.swing.JLabel errorIco;
    private javax.swing.JButton forgotPassword;
    private javax.swing.JLabel loginFailed;
    private javax.swing.JPasswordField login_password;
    private javax.swing.JTextField login_username;
    private javax.swing.JLabel logo;
    private javax.swing.JButton signin_btn;
    private javax.swing.JLabel signupError;
    private javax.swing.JLabel signupSuccess;
    private javax.swing.JLabel signupSuccessIco;
    private javax.swing.JButton signup_btn;
    private javax.swing.JTextField signup_email;
    private javax.swing.JPasswordField signup_password;
    private javax.swing.JTextField signup_username;
    // End of variables declaration//GEN-END:variables
}
