/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Core;

/**
 *
 * @author Shahlin
 */
public class Misc extends javax.swing.JFrame {

    /**
     * Creates new form Misc
     */
    public Misc() {
        initComponents();
        tansferDarkLogo.setVisible(false);
        readerDarkLogo.setVisible(false);
        setLocationRelativeTo(null);
        
        walletUnderline.setVisible(false);
        remindersUnderline.setVisible(false);
        notesUnderline.setVisible(false);
        quickLinksUnderline.setVisible(false);
        newsUnderline.setVisible(false);
        homeUnderline.setVisible(false);
        settingsUnderline.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tansferDarkLogo = new javax.swing.JLabel();
        readerDarkLogo = new javax.swing.JLabel();
        dropDown = new javax.swing.JComboBox<>();
        readerLabel2 = new javax.swing.JLabel();
        readerLabel1 = new javax.swing.JLabel();
        transerLabel2 = new javax.swing.JLabel();
        transferLabel1 = new javax.swing.JLabel();
        newsBtn = new javax.swing.JButton();
        quickLinksBtn = new javax.swing.JButton();
        notesBtn = new javax.swing.JButton();
        remindersBtn = new javax.swing.JButton();
        walletBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        settingsUnderline = new javax.swing.JLabel();
        homeUnderline = new javax.swing.JLabel();
        newsUnderline = new javax.swing.JLabel();
        quickLinksUnderline = new javax.swing.JLabel();
        notesUnderline = new javax.swing.JLabel();
        remindersUnderline = new javax.swing.JLabel();
        walletUnderline = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        tansferDarkLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/transferDark.png"))); // NOI18N
        tansferDarkLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(tansferDarkLogo);
        tansferDarkLogo.setBounds(750, 239, 130, 140);

        readerDarkLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/ereaderDark.png"))); // NOI18N
        readerDarkLogo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(readerDarkLogo);
        readerDarkLogo.setBounds(395, 236, 130, 140);

        dropDown.setBackground(new java.awt.Color(0, 153, 51, 0));
        usersHelper user = new usersHelper();
        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {user.getUsername(user.getLoggedInUser()), "Logout"}));
        dropDown.setOpaque(false);
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });
        getContentPane().add(dropDown);
        dropDown.setBounds(798, 35, 186, 38);

        readerLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        readerLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readerLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readerLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readerLabel2MouseExited(evt);
            }
        });
        getContentPane().add(readerLabel2);
        readerLabel2.setBounds(370, 420, 160, 50);

        readerLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        readerLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                readerLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                readerLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                readerLabel1MouseExited(evt);
            }
        });
        getContentPane().add(readerLabel1);
        readerLabel1.setBounds(330, 238, 255, 140);

        transerLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transerLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transerLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transerLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transerLabel2MouseExited(evt);
            }
        });
        getContentPane().add(transerLabel2);
        transerLabel2.setBounds(720, 420, 187, 50);

        transferLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        transferLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                transferLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                transferLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                transferLabel1MouseExited(evt);
            }
        });
        getContentPane().add(transferLabel1);
        transferLabel1.setBounds(686, 238, 255, 140);

        newsBtn.setBorder(null);
        newsBtn.setBorderPainted(false);
        newsBtn.setContentAreaFilled(false);
        newsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        newsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                newsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                newsBtnMouseExited(evt);
            }
        });
        newsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(newsBtn);
        newsBtn.setBounds(30, 470, 200, 50);

        quickLinksBtn.setBorder(null);
        quickLinksBtn.setBorderPainted(false);
        quickLinksBtn.setContentAreaFilled(false);
        quickLinksBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        quickLinksBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                quickLinksBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                quickLinksBtnMouseExited(evt);
            }
        });
        quickLinksBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quickLinksBtnActionPerformed(evt);
            }
        });
        getContentPane().add(quickLinksBtn);
        quickLinksBtn.setBounds(30, 410, 200, 40);

        notesBtn.setBorder(null);
        notesBtn.setBorderPainted(false);
        notesBtn.setContentAreaFilled(false);
        notesBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        notesBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notesBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                notesBtnMouseExited(evt);
            }
        });
        notesBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notesBtnActionPerformed(evt);
            }
        });
        getContentPane().add(notesBtn);
        notesBtn.setBounds(30, 340, 190, 40);

        remindersBtn.setBorder(null);
        remindersBtn.setBorderPainted(false);
        remindersBtn.setContentAreaFilled(false);
        remindersBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        remindersBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                remindersBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                remindersBtnMouseExited(evt);
            }
        });
        remindersBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                remindersBtnActionPerformed(evt);
            }
        });
        getContentPane().add(remindersBtn);
        remindersBtn.setBounds(30, 270, 190, 50);

        walletBtn.setBorder(null);
        walletBtn.setBorderPainted(false);
        walletBtn.setContentAreaFilled(false);
        walletBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        walletBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                walletBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                walletBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                walletBtnMouseExited(evt);
            }
        });
        walletBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                walletBtnActionPerformed(evt);
            }
        });
        getContentPane().add(walletBtn);
        walletBtn.setBounds(30, 200, 160, 50);

        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(390, 30, 110, 43);

        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(settingsBtn);
        settingsBtn.setBounds(590, 30, 140, 40);

        settingsUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/settingsUnderline.png"))); // NOI18N
        getContentPane().add(settingsUnderline);
        settingsUnderline.setBounds(640, 70, 80, 10);

        homeUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/homeUnderline.png"))); // NOI18N
        getContentPane().add(homeUnderline);
        homeUnderline.setBounds(443, 70, 80, 10);

        newsUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/newsUnderline.png"))); // NOI18N
        getContentPane().add(newsUnderline);
        newsUnderline.setBounds(94, 510, 80, 20);

        quickLinksUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/quickLinksUnderline.png"))); // NOI18N
        getContentPane().add(quickLinksUnderline);
        quickLinksUnderline.setBounds(90, 444, 150, 20);

        notesUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/notesUnderline.png"))); // NOI18N
        notesUnderline.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                notesUnderlineMouseEntered(evt);
            }
        });
        getContentPane().add(notesUnderline);
        notesUnderline.setBounds(94, 370, 80, 20);

        remindersUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/remindersUnderline.png"))); // NOI18N
        getContentPane().add(remindersUnderline);
        remindersUnderline.setBounds(90, 310, 130, 10);

        walletUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/walletUnderline.jpg"))); // NOI18N
        getContentPane().add(walletUnderline);
        walletUnderline.setBounds(100, 240, 80, 10);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Misc.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1040, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:

        if (dropDown.getSelectedItem().equals("Logout")) {
            usersHelper user = new usersHelper();
            user.logout();
            this.setVisible(false);
            dispose();

            Login window = new Login();
            window.setVisible(true);
        }
    }//GEN-LAST:event_dropDownActionPerformed

    private void readerLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerLabel2MouseClicked
        // TODO add your handling code here:
        pdfreaderHelper helper = new pdfreaderHelper();
        usersHelper user = new usersHelper();
        
        helper.incrementUsageCount(user.getLoggedInUser());
        
        PDFReader window = new PDFReader();
        
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_readerLabel2MouseClicked

    private void readerLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerLabel1MouseClicked
        // TODO add your handling code here:
        pdfreaderHelper helper = new pdfreaderHelper();
        usersHelper user = new usersHelper();
        
        helper.incrementUsageCount(user.getLoggedInUser());
        
        PDFReader window = new PDFReader();
        
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_readerLabel1MouseClicked

    private void readerLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerLabel1MouseEntered
        // TODO add your handling code here:
        readerDarkLogo.setVisible(true);
    }//GEN-LAST:event_readerLabel1MouseEntered

    private void readerLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerLabel2MouseEntered
        // TODO add your handling code here:
        readerDarkLogo.setVisible(true);
    }//GEN-LAST:event_readerLabel2MouseEntered

    private void readerLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerLabel1MouseExited
        // TODO add your handling code here:
        readerDarkLogo.setVisible(false);
    }//GEN-LAST:event_readerLabel1MouseExited

    private void readerLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_readerLabel2MouseExited
        // TODO add your handling code here:
        readerDarkLogo.setVisible(false);
    }//GEN-LAST:event_readerLabel2MouseExited

    private void transferLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferLabel1MouseClicked
        // TODO add your handling code here:
        TransferFile window = new TransferFile();
        
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transferLabel1MouseClicked

    private void transerLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transerLabel2MouseClicked
        // TODO add your handling code here:
        TransferFile window = new TransferFile();
        
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_transerLabel2MouseClicked

    private void transferLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferLabel1MouseEntered
        // TODO add your handling code here:
        tansferDarkLogo.setVisible(true);
    }//GEN-LAST:event_transferLabel1MouseEntered

    private void transerLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transerLabel2MouseEntered
        // TODO add your handling code here:
        tansferDarkLogo.setVisible(true);
    }//GEN-LAST:event_transerLabel2MouseEntered

    private void transferLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transferLabel1MouseExited
        // TODO add your handling code here:
        tansferDarkLogo.setVisible(false);
    }//GEN-LAST:event_transferLabel1MouseExited

    private void transerLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_transerLabel2MouseExited
        // TODO add your handling code here:
        tansferDarkLogo.setVisible(false);
    }//GEN-LAST:event_transerLabel2MouseExited

    private void newsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsBtnMouseEntered
        // TODO add your handling code here:
        newsUnderline.setVisible(true);
    }//GEN-LAST:event_newsBtnMouseEntered

    private void newsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newsBtnMouseExited
        // TODO add your handling code here:
        newsUnderline.setVisible(false);
    }//GEN-LAST:event_newsBtnMouseExited

    private void newsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newsBtnActionPerformed
        // TODO add your handling code here:
        News window = new News();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_newsBtnActionPerformed

    private void quickLinksBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickLinksBtnMouseEntered
        // TODO add your handling code here:
        quickLinksUnderline.setVisible(true);
    }//GEN-LAST:event_quickLinksBtnMouseEntered

    private void quickLinksBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_quickLinksBtnMouseExited
        // TODO add your handling code here:
        quickLinksUnderline.setVisible(false);
    }//GEN-LAST:event_quickLinksBtnMouseExited

    private void quickLinksBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quickLinksBtnActionPerformed
        // TODO add your handling code here:
        quicklinksHelper helper = new quicklinksHelper();
        usersHelper user = new usersHelper();

        helper.incrementUsageCount(user.getLoggedInUser());

        QuickLinks window = new QuickLinks();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_quickLinksBtnActionPerformed

    private void notesBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesBtnMouseEntered
        // TODO add your handling code here:
        notesUnderline.setVisible(true);
    }//GEN-LAST:event_notesBtnMouseEntered

    private void notesBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesBtnMouseExited
        // TODO add your handling code here:
        notesUnderline.setVisible(false);
    }//GEN-LAST:event_notesBtnMouseExited

    private void notesBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notesBtnActionPerformed
        // TODO add your handling code here:
        notesHelper helper = new notesHelper();
        usersHelper user = new usersHelper();

        helper.incrementUsageCount(user.getLoggedInUser());

        Notes window = new Notes();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_notesBtnActionPerformed

    private void remindersBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remindersBtnMouseEntered
        // TODO add your handling code here:
        remindersUnderline.setVisible(true);
    }//GEN-LAST:event_remindersBtnMouseEntered

    private void remindersBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_remindersBtnMouseExited
        // TODO add your handling code here:
        remindersUnderline.setVisible(false);
    }//GEN-LAST:event_remindersBtnMouseExited

    private void remindersBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_remindersBtnActionPerformed
        // TODO add your handling code here:
        Reminders window = new Reminders();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_remindersBtnActionPerformed

    private void walletBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_walletBtnMouseClicked

    private void walletBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletBtnMouseEntered
        // TODO add your handling code here:
        walletUnderline.setVisible(true);
    }//GEN-LAST:event_walletBtnMouseEntered

    private void walletBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_walletBtnMouseExited
        // TODO add your handling code here:
        walletUnderline.setVisible(false);
    }//GEN-LAST:event_walletBtnMouseExited

    private void walletBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_walletBtnActionPerformed
        // TODO add your handling code here:
        walletHelper helper = new walletHelper();
        usersHelper user = new usersHelper();

        helper.incrementUsageCount(user.getLoggedInUser());

        Wallet window = new Wallet();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_walletBtnActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        // TODO add your handling code here:
        homeUnderline.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        // TODO add your handling code here:
        homeUnderline.setVisible(false);
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Home window = new Home();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        // TODO add your handling code here:
        settingsUnderline.setVisible(true);
    }//GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
        // TODO add your handling code here:
        settingsUnderline.setVisible(false);
    }//GEN-LAST:event_settingsBtnMouseExited

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void notesUnderlineMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notesUnderlineMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_notesUnderlineMouseEntered

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Misc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Misc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Misc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Misc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Misc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel homeUnderline;
    private javax.swing.JButton newsBtn;
    private javax.swing.JLabel newsUnderline;
    private javax.swing.JButton notesBtn;
    private javax.swing.JLabel notesUnderline;
    private javax.swing.JButton quickLinksBtn;
    private javax.swing.JLabel quickLinksUnderline;
    private javax.swing.JLabel readerDarkLogo;
    private javax.swing.JLabel readerLabel1;
    private javax.swing.JLabel readerLabel2;
    private javax.swing.JButton remindersBtn;
    private javax.swing.JLabel remindersUnderline;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsUnderline;
    private javax.swing.JLabel tansferDarkLogo;
    private javax.swing.JLabel transerLabel2;
    private javax.swing.JLabel transferLabel1;
    private javax.swing.JButton walletBtn;
    private javax.swing.JLabel walletUnderline;
    // End of variables declaration//GEN-END:variables
}
