package Core;


import com.sun.syndication.feed.synd.SyndEntry;
import com.sun.syndication.feed.synd.SyndFeed;
import com.sun.syndication.io.FeedException;
import com.sun.syndication.io.SyndFeedInput;
import com.sun.syndication.io.XmlReader;
import java.io.IOException;
import java.net.HttpURLConnection;
import java.net.MalformedURLException;
import java.net.URI;
import java.net.URL;
import java.util.Iterator;
import java.util.List;
import javax.swing.JTextPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahlin
 */
public class News extends javax.swing.JFrame {

    /**
     * Creates new form News
     */
    
    private String readMoreURL = "http://www.reuters.com/news/archive/topNews";
    
    public News() {
        initComponents();
        setResizable(false);
        setLocationRelativeTo(null);
        
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane5.setVisible(false);
        
        homeUnderline.setVisible(false);
        settingsUnderline.setVisible(false);
        
        displayNews("http://feeds.reuters.com/reuters/topNews", topNewsContainer);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        topNewsContainer = new javax.swing.JTextPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        entertainmentContainer = new javax.swing.JTextPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        sportsContainer = new javax.swing.JTextPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        techContainer = new javax.swing.JTextPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        worldContainer = new javax.swing.JTextPane();
        worldBtn = new javax.swing.JButton();
        techBtn = new javax.swing.JButton();
        sportsBtn = new javax.swing.JButton();
        entertainmentBtn = new javax.swing.JButton();
        topNewsBtn = new javax.swing.JButton();
        dropDown = new javax.swing.JComboBox<>();
        readMoreBtn = new javax.swing.JButton();
        homeUnderline = new javax.swing.JLabel();
        settingsUnderline = new javax.swing.JLabel();
        settingsBtn = new javax.swing.JButton();
        homeBtn = new javax.swing.JButton();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        addWindowStateListener(new java.awt.event.WindowStateListener() {
            public void windowStateChanged(java.awt.event.WindowEvent evt) {
                formWindowStateChanged(evt);
            }
        });
        getContentPane().setLayout(null);

        jScrollPane1.setBackground(new java.awt.Color(248, 248, 248));
        jScrollPane1.setBorder(null);

        topNewsContainer.setEditable(false);
        topNewsContainer.setBackground(new java.awt.Color(248, 248, 248));
        topNewsContainer.setBorder(null);
        jScrollPane1.setViewportView(topNewsContainer);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 170, 610, 410);

        jScrollPane2.setBackground(new java.awt.Color(248, 248, 248));
        jScrollPane2.setBorder(null);

        entertainmentContainer.setEditable(false);
        entertainmentContainer.setBackground(new java.awt.Color(248, 248, 248));
        entertainmentContainer.setBorder(null);
        jScrollPane2.setViewportView(entertainmentContainer);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 170, 610, 410);

        jScrollPane3.setBackground(new java.awt.Color(248, 248, 248));
        jScrollPane3.setBorder(null);

        sportsContainer.setEditable(false);
        sportsContainer.setBackground(new java.awt.Color(248, 248, 248));
        sportsContainer.setBorder(null);
        jScrollPane3.setViewportView(sportsContainer);

        getContentPane().add(jScrollPane3);
        jScrollPane3.setBounds(350, 170, 610, 410);

        jScrollPane4.setBackground(new java.awt.Color(248, 248, 248));
        jScrollPane4.setBorder(null);

        techContainer.setEditable(false);
        techContainer.setBackground(new java.awt.Color(248, 248, 248));
        techContainer.setBorder(null);
        jScrollPane4.setViewportView(techContainer);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(350, 170, 610, 410);

        jScrollPane5.setBackground(new java.awt.Color(248, 248, 248));
        jScrollPane5.setBorder(null);

        worldContainer.setEditable(false);
        worldContainer.setBackground(new java.awt.Color(248, 248, 248));
        worldContainer.setBorder(null);
        jScrollPane5.setViewportView(worldContainer);

        getContentPane().add(jScrollPane5);
        jScrollPane5.setBounds(350, 170, 610, 410);

        worldBtn.setBorder(null);
        worldBtn.setBorderPainted(false);
        worldBtn.setContentAreaFilled(false);
        worldBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        worldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                worldBtnActionPerformed(evt);
            }
        });
        getContentPane().add(worldBtn);
        worldBtn.setBounds(40, 523, 240, 60);

        techBtn.setBorder(null);
        techBtn.setBorderPainted(false);
        techBtn.setContentAreaFilled(false);
        techBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        techBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                techBtnActionPerformed(evt);
            }
        });
        getContentPane().add(techBtn);
        techBtn.setBounds(40, 440, 240, 60);

        sportsBtn.setBorder(null);
        sportsBtn.setBorderPainted(false);
        sportsBtn.setContentAreaFilled(false);
        sportsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        sportsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sportsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(sportsBtn);
        sportsBtn.setBounds(40, 350, 240, 60);

        entertainmentBtn.setBorder(null);
        entertainmentBtn.setBorderPainted(false);
        entertainmentBtn.setContentAreaFilled(false);
        entertainmentBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        entertainmentBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                entertainmentBtnActionPerformed(evt);
            }
        });
        getContentPane().add(entertainmentBtn);
        entertainmentBtn.setBounds(50, 260, 240, 60);

        topNewsBtn.setBorder(null);
        topNewsBtn.setBorderPainted(false);
        topNewsBtn.setContentAreaFilled(false);
        topNewsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        topNewsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                topNewsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(topNewsBtn);
        topNewsBtn.setBounds(50, 170, 230, 60);

        dropDown.setBackground(new java.awt.Color(0, 153, 51, 0));
        usersHelper user = new usersHelper();
        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {user.getUsername(user.getLoggedInUser()), "Logout"}));
        dropDown.setBorder(null);
        dropDown.setOpaque(false);
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });
        getContentPane().add(dropDown);
        dropDown.setBounds(798, 35, 186, 38);

        readMoreBtn.setBorder(null);
        readMoreBtn.setBorderPainted(false);
        readMoreBtn.setContentAreaFilled(false);
        readMoreBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        readMoreBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readMoreBtnActionPerformed(evt);
            }
        });
        getContentPane().add(readMoreBtn);
        readMoreBtn.setBounds(850, 600, 130, 50);

        homeUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/homeUnderline.png"))); // NOI18N
        getContentPane().add(homeUnderline);
        homeUnderline.setBounds(442, 73, 80, 10);

        settingsUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/settingsUnderline.png"))); // NOI18N
        getContentPane().add(settingsUnderline);
        settingsUnderline.setBounds(640, 73, 80, 10);

        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(settingsBtn);
        settingsBtn.setBounds(585, 35, 140, 40);

        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(388, 32, 110, 43);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/News.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1040, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        jScrollPane1.getVerticalScrollBar().setValue(0);
        jScrollPane2.getVerticalScrollBar().setValue(0);
        jScrollPane3.getVerticalScrollBar().setValue(0);
        jScrollPane4.getVerticalScrollBar().setValue(0);
        jScrollPane5.getVerticalScrollBar().setValue(0);
    }//GEN-LAST:event_formComponentShown

    private void topNewsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_topNewsBtnActionPerformed
        // TODO add your handling code here:
        readMoreURL = "http://www.reuters.com/news/archive/topNews";
        
        jScrollPane1.setVisible(true);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane5.setVisible(false);
    }//GEN-LAST:event_topNewsBtnActionPerformed

    private void entertainmentBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_entertainmentBtnActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        
        displayNews("http://feeds.reuters.com/reuters/entertainment", entertainmentContainer);
        readMoreURL = "http://www.reuters.com/news/entertainment";
        
        jScrollPane2.setVisible(true);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        jScrollPane5.setVisible(false);        
    }//GEN-LAST:event_entertainmentBtnActionPerformed

    private void sportsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sportsBtnActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        
        displayNews("http://feeds.reuters.com/reuters/sportsNews", sportsContainer);
        readMoreURL = "http://www.reuters.com/news/sports";
        
        jScrollPane3.setVisible(true);
        jScrollPane4.setVisible(false);
        jScrollPane5.setVisible(false);
    }//GEN-LAST:event_sportsBtnActionPerformed

    private void techBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_techBtnActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        
        displayNews("http://feeds.reuters.com/reuters/technologyNews", techContainer);
        readMoreURL = "http://www.reuters.com/news/technology";
        
        jScrollPane4.setVisible(true);
        jScrollPane5.setVisible(false);
    }//GEN-LAST:event_techBtnActionPerformed

    private void worldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_worldBtnActionPerformed
        // TODO add your handling code here:
        jScrollPane1.setVisible(false);
        jScrollPane2.setVisible(false);
        jScrollPane3.setVisible(false);
        jScrollPane4.setVisible(false);
        
        displayNews("http://feeds.reuters.com/reuters/worldNews", worldContainer);
        readMoreURL = "http://www.reuters.com/news/world";
        
        jScrollPane5.setVisible(true);
    }//GEN-LAST:event_worldBtnActionPerformed

    private void formWindowStateChanged(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_formWindowStateChanged

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:

        if (dropDown.getSelectedItem().equals("Logout")) {
            usersHelper user = new usersHelper();
            user.logout();
            this.setVisible(false);
            dispose();

            Login window = new Login();
            window.setVisible(true);
        }
    }//GEN-LAST:event_dropDownActionPerformed

    private void readMoreBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readMoreBtnActionPerformed
        try {
            java.awt.Desktop.getDesktop().browse(URI.create(readMoreURL));
        } catch (IOException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_readMoreBtnActionPerformed

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        // TODO add your handling code here:
        settingsUnderline.setVisible(true);
    }//GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
        // TODO add your handling code here:
        settingsUnderline.setVisible(false);
    }//GEN-LAST:event_settingsBtnMouseExited

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        // TODO add your handling code here:
        homeUnderline.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        // TODO add your handling code here:
        homeUnderline.setVisible(false);
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Home window = new Home();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void displayNews(String url, JTextPane tp){
        URL feedUrl = null;
        try {
            feedUrl = new URL(url);
        } catch (MalformedURLException ex) {
           System.out.println(ex);
        }
        
        Util utility = new Util();
        SyndFeedInput input = new SyndFeedInput();
        String news = "<html>";
        
        try {
            HttpURLConnection conn = (HttpURLConnection) feedUrl.openConnection();
            SyndFeed feed = input.build(new XmlReader(conn));
            
            List entries = feed.getEntries();
            Iterator iter = entries.iterator();
            
            while(iter.hasNext()){
                SyndEntry entry = (SyndEntry) iter.next();
                news += "<div style=\"padding:7px;background-color:#f8f8f8;\">";
                news += "<span style=\"color:#4a4841;font-size:14px;\"><b>" + entry.getTitle() + "</b></span>";
                String text = "<br><br>- " + entry.getDescription().getValue();
                
                int occurence = utility.findStringOccurrence(text, "<div class=\"feedflare\">");
                news += text.substring(0, occurence);
                
                news += "<br><br><br>";
                
                news += "</div>";
            }
        } catch (FeedException | IOException | IllegalArgumentException ex) {
            System.out.println(ex);
        }
        
        news += "</html>";
        
        tp.setContentType("text/html");
        tp.setText(news);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(News.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new News().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JButton entertainmentBtn;
    private javax.swing.JTextPane entertainmentContainer;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel homeUnderline;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JButton readMoreBtn;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsUnderline;
    private javax.swing.JButton sportsBtn;
    private javax.swing.JTextPane sportsContainer;
    private javax.swing.JButton techBtn;
    private javax.swing.JTextPane techContainer;
    private javax.swing.JButton topNewsBtn;
    private javax.swing.JTextPane topNewsContainer;
    private javax.swing.JButton worldBtn;
    private javax.swing.JTextPane worldContainer;
    // End of variables declaration//GEN-END:variables
}
