package Core;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author sarah
 */
public class Notes extends javax.swing.JFrame {

    /**
     * Creates new form Notes
     */
    private Connection c = null;

    public Notes() {
        initComponents();
        setLocationRelativeTo(this);
        setResizable(false);
        
        homeUnderline.setVisible(false);
        settingsUnderline.setVisible(false);
        
        displayNotes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        AddNotes_btn = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        notesContainer = new javax.swing.JTextPane();
        quote = new javax.swing.JLabel();
        dropDown = new javax.swing.JComboBox<>();
        homeBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        settingsUnderline = new javax.swing.JLabel();
        homeUnderline = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 700));
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });
        getContentPane().setLayout(null);

        AddNotes_btn.setBorder(null);
        AddNotes_btn.setBorderPainted(false);
        AddNotes_btn.setContentAreaFilled(false);
        AddNotes_btn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        AddNotes_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddNotes_btnActionPerformed(evt);
            }
        });
        getContentPane().add(AddNotes_btn);
        AddNotes_btn.setBounds(26, 196, 190, 53);

        jScrollPane4.setBackground(new java.awt.Color(204, 51, 0));
        jScrollPane4.setBorder(null);

        notesContainer.setEditable(false);
        notesContainer.setBackground(new java.awt.Color(251, 255, 233));
        notesContainer.setBorder(null);
        jScrollPane4.setViewportView(notesContainer);
        jScrollPane4.setViewportBorder(null);

        getContentPane().add(jScrollPane4);
        jScrollPane4.setBounds(335, 169, 647, 370);

        quote.setFont(new java.awt.Font("Arial", 2, 16)); // NOI18N
        getContentPane().add(quote);
        quote.setBounds(60, 280, 180, 220);

        dropDown.setBackground(new java.awt.Color(0, 153, 51, 0));
        usersHelper user = new usersHelper();
        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {user.getUsername(user.getLoggedInUser()), "Logout"}));
        dropDown.setBorder(null);
        dropDown.setOpaque(false);
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });
        getContentPane().add(dropDown);
        dropDown.setBounds(798, 30, 186, 38);

        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(388, 32, 110, 43);

        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(settingsBtn);
        settingsBtn.setBounds(585, 35, 140, 40);

        settingsUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/settingsUnderline.png"))); // NOI18N
        getContentPane().add(settingsUnderline);
        settingsUnderline.setBounds(640, 67, 80, 10);

        homeUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/homeUnderline.png"))); // NOI18N
        getContentPane().add(homeUnderline);
        homeUnderline.setBounds(442, 67, 80, 10);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Notes.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, -10, 1040, 710);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddNotes_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddNotes_btnActionPerformed
        // TODO add your handling code here:
        addNote add = new addNote();
        add.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddNotes_btnActionPerformed

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:

        if (dropDown.getSelectedItem().equals("Logout")) {
            usersHelper user = new usersHelper();
            user.logout();
            this.setVisible(false);
            dispose();

            Login window = new Login();
            window.setVisible(true);
        }
    }//GEN-LAST:event_dropDownActionPerformed

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        // TODO add your handling code here:
        jScrollPane4.getVerticalScrollBar().setValue(0);
    }//GEN-LAST:event_formComponentShown

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        // TODO add your handling code here:
        homeUnderline.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        // TODO add your handling code here:
        homeUnderline.setVisible(false);
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Home window = new Home();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        // TODO add your handling code here:
        settingsUnderline.setVisible(true);
    }//GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
        // TODO add your handling code here:
        settingsUnderline.setVisible(false);
    }//GEN-LAST:event_settingsBtnMouseExited

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    private void displayNotes() {
        usersHelper user = new usersHelper();
        notesHelper helper = new notesHelper();

        ResultSet notesSet = helper.DisplayNoteInfo(user.getLoggedInUser());
        //Start HTML tag for formatting the content in HTML
        String noteDetails = "<html>";

        boolean divColorFlag = true;

        try {
            while (notesSet.next()) {
                //Get values from table
                String title = notesSet.getString("title");
                String body = notesSet.getString("body");
                String date_posted = notesSet.getString("date_post");

                String date = date_posted.substring(0, 10);
                String time = date_posted.substring(11, date_posted.length() - 2);

                noteDetails += (divColorFlag) ? "<div style=\"background-color:#ece8da;\">" : "<div style=\"background-color:#e6e1d2;\">";

                noteDetails += "<h2 style=\"color:#4a4841;\">" + title + "</h2>";
                noteDetails += "<br>";
                //If body doesn't exist, do not add a line break
                noteDetails += (!body.equals("")) ? "<span style='color:#4a4841;'>" + body + "</span>" : "";
                noteDetails += (!body.equals("")) ? "<br><br>" : "";
                noteDetails += "<span style='color:#87847c;'><i>Posted on " + date + " at " + time + "</i></span>";
                noteDetails += "<br>";
                noteDetails += "<br>";
                noteDetails += "</div>";

                divColorFlag = !divColorFlag;
            }

            notesSet.close();
        } catch (SQLException ex) {
            System.out.println("SQLException: " + ex.getMessage());
            System.out.println("SQLState: " + ex.getSQLState());
        }

        noteDetails += "</html>";
        notesContainer.setContentType("text/html");
        notesContainer.setText(noteDetails);

        //Instantiate Util class to get quotes
        Util util = new Util();

        quote.setText("<html>" + util.printQuote("http://feeds.feedburner.com/brainyquote/QUOTEAR") + "</html>");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddNotes_btn;
    private javax.swing.JLabel background;
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel homeUnderline;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTextPane notesContainer;
    private javax.swing.JLabel quote;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsUnderline;
    // End of variables declaration//GEN-END:variables
}
