package Core;


import java.io.IOException;
import java.net.URISyntaxException;
import java.net.URL;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Shahlin
 */
public class QuickLinks extends javax.swing.JFrame {

    /**
     * Creates new form QuickLinks
     */
    
    String url1 = "", url2 = "", url3 = "", url4 = "";
    int count = 0;
    
    public QuickLinks() {
        initComponents();
        setLocationRelativeTo(null);
        
        link1.setEnabled(false);
        link2.setEnabled(false);
        link3.setEnabled(false);
        link4.setEnabled(false);
        
        deleteLink1.setVisible(false);
        deleteLink2.setVisible(false);
        deleteLink3.setVisible(false);
        deleteLink4.setVisible(false);
        deleteLinkLabel1.setVisible(false);
        deleteLinkLabel2.setVisible(false);
        deleteLinkLabel3.setVisible(false);
        deleteLinkLabel4.setVisible(false);
        
        addressBarError.setVisible(false);
        
        homeUnderline.setVisible(false);
        settingsUnderline.setVisible(false);
        
        setWebsitesData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        webInput = new javax.swing.JTextField();
        openWebsite = new javax.swing.JButton();
        addLinkBtn = new javax.swing.JButton();
        google = new javax.swing.JButton();
        youtube = new javax.swing.JButton();
        facebook = new javax.swing.JButton();
        amazon = new javax.swing.JButton();
        reddit = new javax.swing.JButton();
        twitter = new javax.swing.JButton();
        yahoo = new javax.swing.JButton();
        hotmail = new javax.swing.JButton();
        Gmail = new javax.swing.JButton();
        link1 = new javax.swing.JButton();
        link2 = new javax.swing.JButton();
        link3 = new javax.swing.JButton();
        link4 = new javax.swing.JButton();
        deleteLinkLabel4 = new javax.swing.JLabel();
        deleteLink4 = new javax.swing.JLabel();
        deleteLinkLabel3 = new javax.swing.JLabel();
        deleteLink3 = new javax.swing.JLabel();
        deleteLinkLabel2 = new javax.swing.JLabel();
        deleteLink2 = new javax.swing.JLabel();
        deleteLinkLabel1 = new javax.swing.JLabel();
        deleteLink1 = new javax.swing.JLabel();
        addressBarError = new javax.swing.JLabel();
        dropDown = new javax.swing.JComboBox<>();
        homeBtn = new javax.swing.JButton();
        settingsBtn = new javax.swing.JButton();
        settingsUnderline = new javax.swing.JLabel();
        homeUnderline = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1040, 700));
        setResizable(false);
        getContentPane().setLayout(null);

        webInput.setBackground(new java.awt.Color(243, 240, 231));
        webInput.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        webInput.setForeground(new java.awt.Color(74, 72, 65));
        webInput.setText("Enter a website");
        webInput.setBorder(null);
        webInput.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                webInputFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                webInputFocusLost(evt);
            }
        });
        getContentPane().add(webInput);
        webInput.setBounds(342, 583, 493, 40);

        openWebsite.setBorder(null);
        openWebsite.setBorderPainted(false);
        openWebsite.setContentAreaFilled(false);
        openWebsite.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        openWebsite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openWebsiteActionPerformed(evt);
            }
        });
        getContentPane().add(openWebsite);
        openWebsite.setBounds(878, 579, 46, 46);

        addLinkBtn.setBorder(null);
        addLinkBtn.setBorderPainted(false);
        addLinkBtn.setContentAreaFilled(false);
        addLinkBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addLinkBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addLinkBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addLinkBtn);
        addLinkBtn.setBounds(26, 200, 180, 54);

        google.setBorder(null);
        google.setBorderPainted(false);
        google.setContentAreaFilled(false);
        google.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        google.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                googleActionPerformed(evt);
            }
        });
        getContentPane().add(google);
        google.setBounds(411, 177, 70, 80);

        youtube.setBorder(null);
        youtube.setBorderPainted(false);
        youtube.setContentAreaFilled(false);
        youtube.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        youtube.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                youtubeActionPerformed(evt);
            }
        });
        getContentPane().add(youtube);
        youtube.setBounds(714, 177, 80, 80);

        facebook.setBorder(null);
        facebook.setBorderPainted(false);
        facebook.setContentAreaFilled(false);
        facebook.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        facebook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                facebookActionPerformed(evt);
            }
        });
        getContentPane().add(facebook);
        facebook.setBounds(397, 300, 100, 90);

        amazon.setBorder(null);
        amazon.setBorderPainted(false);
        amazon.setContentAreaFilled(false);
        amazon.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        amazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                amazonActionPerformed(evt);
            }
        });
        getContentPane().add(amazon);
        amazon.setBounds(716, 430, 80, 100);

        reddit.setBorder(null);
        reddit.setBorderPainted(false);
        reddit.setContentAreaFilled(false);
        reddit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        reddit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redditActionPerformed(evt);
            }
        });
        getContentPane().add(reddit);
        reddit.setBounds(563, 430, 70, 100);

        twitter.setBorder(null);
        twitter.setBorderPainted(false);
        twitter.setContentAreaFilled(false);
        twitter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        twitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                twitterActionPerformed(evt);
            }
        });
        getContentPane().add(twitter);
        twitter.setBounds(407, 430, 80, 100);

        yahoo.setBorder(null);
        yahoo.setBorderPainted(false);
        yahoo.setContentAreaFilled(false);
        yahoo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        yahoo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yahooActionPerformed(evt);
            }
        });
        getContentPane().add(yahoo);
        yahoo.setBounds(717, 300, 70, 90);

        hotmail.setBorder(null);
        hotmail.setBorderPainted(false);
        hotmail.setContentAreaFilled(false);
        hotmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        hotmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hotmailActionPerformed(evt);
            }
        });
        getContentPane().add(hotmail);
        hotmail.setBounds(561, 300, 80, 100);

        Gmail.setBorder(null);
        Gmail.setBorderPainted(false);
        Gmail.setContentAreaFilled(false);
        Gmail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Gmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GmailActionPerformed(evt);
            }
        });
        getContentPane().add(Gmail);
        Gmail.setBounds(568, 177, 60, 80);

        link1.setBackground(new java.awt.Color(74, 72, 65));
        link1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        link1.setBorder(null);
        link1.setBorderPainted(false);
        link1.setContentAreaFilled(false);
        link1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link1ActionPerformed(evt);
            }
        });
        getContentPane().add(link1);
        link1.setBounds(80, 280, 132, 48);

        link2.setBackground(new java.awt.Color(74, 72, 65));
        link2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        link2.setBorder(null);
        link2.setBorderPainted(false);
        link2.setContentAreaFilled(false);
        link2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link2ActionPerformed(evt);
            }
        });
        getContentPane().add(link2);
        link2.setBounds(80, 350, 132, 53);

        link3.setBackground(new java.awt.Color(74, 72, 65));
        link3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        link3.setBorder(null);
        link3.setBorderPainted(false);
        link3.setContentAreaFilled(false);
        link3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link3ActionPerformed(evt);
            }
        });
        getContentPane().add(link3);
        link3.setBounds(73, 420, 140, 48);

        link4.setBackground(new java.awt.Color(74, 72, 65));
        link4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        link4.setBorder(null);
        link4.setBorderPainted(false);
        link4.setContentAreaFilled(false);
        link4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        link4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                link4ActionPerformed(evt);
            }
        });
        getContentPane().add(link4);
        link4.setBounds(80, 490, 131, 44);

        deleteLinkLabel4.setForeground(new java.awt.Color(0,0,0,0));
        deleteLinkLabel4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLinkLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLinkLabel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteLinkLabel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteLinkLabel4MouseExited(evt);
            }
        });
        getContentPane().add(deleteLinkLabel4);
        deleteLinkLabel4.setBounds(36, 497, 35, 40);

        deleteLink4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1494028560_minus.png"))); // NOI18N
        deleteLink4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(deleteLink4);
        deleteLink4.setBounds(36, 497, 35, 40);

        deleteLinkLabel3.setForeground(new java.awt.Color(0,0,0,0));
        deleteLinkLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLinkLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLinkLabel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteLinkLabel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteLinkLabel3MouseExited(evt);
            }
        });
        getContentPane().add(deleteLinkLabel3);
        deleteLinkLabel3.setBounds(36, 423, 35, 40);

        deleteLink3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1494028560_minus.png"))); // NOI18N
        deleteLink3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        getContentPane().add(deleteLink3);
        deleteLink3.setBounds(36, 423, 35, 40);

        deleteLinkLabel2.setForeground(new java.awt.Color(0,0,0,0));
        deleteLinkLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLinkLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLinkLabel2MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteLinkLabel2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteLinkLabel2MouseExited(evt);
            }
        });
        getContentPane().add(deleteLinkLabel2);
        deleteLinkLabel2.setBounds(36, 351, 35, 40);

        deleteLink2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1494028560_minus.png"))); // NOI18N
        deleteLink2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLink2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLink2MouseClicked(evt);
            }
        });
        getContentPane().add(deleteLink2);
        deleteLink2.setBounds(36, 351, 35, 40);

        deleteLinkLabel1.setForeground(new java.awt.Color(0,0,0,0));
        deleteLinkLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLinkLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLinkLabel1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                deleteLinkLabel1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                deleteLinkLabel1MouseExited(evt);
            }
        });
        getContentPane().add(deleteLinkLabel1);
        deleteLinkLabel1.setBounds(36, 284, 35, 40);

        deleteLink1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/1494028560_minus.png"))); // NOI18N
        deleteLink1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteLink1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteLink1MouseClicked(evt);
            }
        });
        getContentPane().add(deleteLink1);
        deleteLink1.setBounds(36, 284, 35, 40);

        addressBarError.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/addressBarErro.png"))); // NOI18N
        getContentPane().add(addressBarError);
        addressBarError.setBounds(334, 577, 510, 50);

        dropDown.setBackground(new java.awt.Color(0, 153, 51, 0));
        usersHelper user = new usersHelper();
        dropDown.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {user.getUsername(user.getLoggedInUser()), "Logout"}));
        dropDown.setOpaque(false);
        dropDown.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dropDownActionPerformed(evt);
            }
        });
        getContentPane().add(dropDown);
        dropDown.setBounds(798, 35, 186, 38);

        homeBtn.setBorder(null);
        homeBtn.setBorderPainted(false);
        homeBtn.setContentAreaFilled(false);
        homeBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeBtnMouseExited(evt);
            }
        });
        homeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                homeBtnActionPerformed(evt);
            }
        });
        getContentPane().add(homeBtn);
        homeBtn.setBounds(388, 32, 110, 43);

        settingsBtn.setBorder(null);
        settingsBtn.setBorderPainted(false);
        settingsBtn.setContentAreaFilled(false);
        settingsBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        settingsBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsBtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsBtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsBtnMouseExited(evt);
            }
        });
        settingsBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                settingsBtnActionPerformed(evt);
            }
        });
        getContentPane().add(settingsBtn);
        settingsBtn.setBounds(585, 35, 140, 40);

        settingsUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/settingsUnderline.png"))); // NOI18N
        getContentPane().add(settingsUnderline);
        settingsUnderline.setBounds(640, 73, 80, 10);

        homeUnderline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/Extras/Underlines/homeUnderline.png"))); // NOI18N
        getContentPane().add(homeUnderline);
        homeUnderline.setBounds(442, 73, 80, 10);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/backgrounds/QuickLinks.jpg"))); // NOI18N
        getContentPane().add(background);
        background.setBounds(0, 0, 1040, 700);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void setWebsitesData(){
        quicklinksHelper helper = new quicklinksHelper();
        usersHelper user = new usersHelper();
        
        int user_id = user.getLoggedInUser();
        
        //Get row count
        int linksCount = helper.webNum(user_id);
        
        if(linksCount == 1){
            link1.setText(helper.getWebNames(user_id)[0]);
            url1 = helper.getWebLinks(user_id)[0];
            
            deleteLinkLabel1.setVisible(true);
            deleteLinkLabel1.setText(""+helper.getLinkIDs(user_id)[0]);
            link1.setEnabled(true);
            count = 1;
            
        } else if(linksCount == 2){
            link1.setText(helper.getWebNames(user_id)[0]);
            link2.setText(helper.getWebNames(user_id)[1]);
            
            url1 = helper.getWebLinks(user_id)[0];
            url2 = helper.getWebLinks(user_id)[1];
            
            deleteLinkLabel1.setVisible(true);
            deleteLinkLabel2.setVisible(true);
            
            deleteLinkLabel1.setText(""+helper.getLinkIDs(user_id)[0]);
            deleteLinkLabel2.setText(""+helper.getLinkIDs(user_id)[1]);
            link1.setEnabled(true);
            link2.setEnabled(true);
            count = 2;
        } else if(linksCount == 3){
            link1.setText(helper.getWebNames(user_id)[0]);
            link2.setText(helper.getWebNames(user_id)[1]);
            link3.setText(helper.getWebNames(user_id)[2]);
            
            url1 = helper.getWebLinks(user_id)[0];
            url2 = helper.getWebLinks(user_id)[1];
            url3 = helper.getWebLinks(user_id)[2];
            
            deleteLinkLabel1.setVisible(true);
            deleteLinkLabel2.setVisible(true);
            deleteLinkLabel3.setVisible(true);
            
            deleteLinkLabel1.setText(""+helper.getLinkIDs(user_id)[0]);
            deleteLinkLabel2.setText(""+helper.getLinkIDs(user_id)[1]);
            deleteLinkLabel3.setText(""+helper.getLinkIDs(user_id)[2]);
            link1.setEnabled(true);
            link2.setEnabled(true);
            link3.setEnabled(true);
            count = 3;
        } else if(linksCount == 4){
            addLinkBtn.setEnabled(false);
            
            link1.setText(helper.getWebNames(user_id)[0]);
            link2.setText(helper.getWebNames(user_id)[1]);
            link3.setText(helper.getWebNames(user_id)[2]);
            link4.setText(helper.getWebNames(user_id)[3]);
            
            url1 = helper.getWebLinks(user_id)[0];
            url2 = helper.getWebLinks(user_id)[1];
            url3 = helper.getWebLinks(user_id)[2];
            url4 = helper.getWebLinks(user_id)[3];
            
            deleteLinkLabel1.setVisible(true);
            deleteLinkLabel2.setVisible(true);
            deleteLinkLabel3.setVisible(true);
            deleteLinkLabel4.setVisible(true);
            
            deleteLinkLabel1.setText(""+helper.getLinkIDs(user_id)[0]);
            deleteLinkLabel2.setText(""+helper.getLinkIDs(user_id)[1]);
            deleteLinkLabel3.setText(""+helper.getLinkIDs(user_id)[2]);
            deleteLinkLabel4.setText(""+helper.getLinkIDs(user_id)[3]);
            link1.setEnabled(true);
            link2.setEnabled(true);
            link3.setEnabled(true);
            link4.setEnabled(true);
            
            count = 4;
        }
        
    }
    
    private void openWebsiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openWebsiteActionPerformed
        // TODO add your handling code here:
        String input = webInput.getText().trim();
        Validation validate = new Validation();
        Util utility = new Util();
        
        boolean error = false;
        
        int httpPos = utility.findStringOccurrence(input, "http://");
        int httpsPos = utility.findStringOccurrence(input, "https://");
        int wwwPos = utility.findStringOccurrence(input, "www.");
        
        if(httpPos == -1 && httpsPos == -1){
            //Doesn't exist in the user input
            if(wwwPos == -1){
                input = "http://www." + input;
            } else {
                input = "http://" + input;
            }
        }
        
        if(validate.validateURL(input) == false || validate.stringIsEmpty(input) == true){
            error = true;
            addressBarError.setVisible(true);
        }
        
        if(error == false){
            try {
                addressBarError.setVisible(false);
                java.awt.Desktop.getDesktop().browse(new URL(input).toURI());
            } catch (IOException | URISyntaxException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_openWebsiteActionPerformed

    private void googleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_googleActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.google.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_googleActionPerformed

    private void youtubeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_youtubeActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.youtube.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_youtubeActionPerformed

    private void facebookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_facebookActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.facebook.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_facebookActionPerformed

    private void hotmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hotmailActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.hotmail.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_hotmailActionPerformed

    private void link1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link1ActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL(url1).toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link1ActionPerformed

    private void link2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link2ActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL(url2).toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link2ActionPerformed

    private void GmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GmailActionPerformed
        // TODO add your handling code here:
        try {
            quicklinksHelper user = new quicklinksHelper();
            java.awt.Desktop.getDesktop().browse(new URL("http://www.gmail.com").toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_GmailActionPerformed

    private void link3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link3ActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL(url3).toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link3ActionPerformed

    private void link4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_link4ActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL(url4).toURI());
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_link4ActionPerformed

    private void yahooActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yahooActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.yahoo.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_yahooActionPerformed

    private void twitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_twitterActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.twitter.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_twitterActionPerformed

    private void redditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redditActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.reddit.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_redditActionPerformed

    private void amazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_amazonActionPerformed
        // TODO add your handling code here:
        try {
            java.awt.Desktop.getDesktop().browse(new URL("http://www.amazon.com").toURI());
        } catch (IOException | URISyntaxException e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_amazonActionPerformed

    private void addLinkBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addLinkBtnActionPerformed
        // TODO add your handling code here:
        addLink window = new addLink();
        this.setVisible(false);
        window.setVisible(true);
    }//GEN-LAST:event_addLinkBtnActionPerformed

    private void webInputFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_webInputFocusGained
        // TODO add your handling code here:
        String website = webInput.getText();

        if (website.equals("Enter a website")) {
            webInput.setText("");
        }
    }//GEN-LAST:event_webInputFocusGained

    private void webInputFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_webInputFocusLost
        // TODO add your handling code here:
        String website = webInput.getText();

        if (website.equals("")) {
            //Default username
            webInput.setText("Enter a website");
        }
    }//GEN-LAST:event_webInputFocusLost

    private void deleteLinkLabel2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel2MouseEntered
        // TODO add your handling code here:
        if(count >= 2){
            deleteLink2.setVisible(true);
            deleteLink1.setVisible(false);
            deleteLink3.setVisible(false);
            deleteLink4.setVisible(false);
        }
    }//GEN-LAST:event_deleteLinkLabel2MouseEntered

    private void deleteLinkLabel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel3MouseEntered
        // TODO add your handling code here:
        if(count >= 3){    
            deleteLink3.setVisible(true);
            deleteLink1.setVisible(false);
            deleteLink2.setVisible(false);
            deleteLink4.setVisible(false);
        }
    }//GEN-LAST:event_deleteLinkLabel3MouseEntered

    private void deleteLinkLabel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel4MouseEntered
        // TODO add your handling code here:
        if(count == 4){
            deleteLink4.setVisible(true);
            deleteLink1.setVisible(false);
            deleteLink2.setVisible(false);
            deleteLink3.setVisible(false);
        }
    }//GEN-LAST:event_deleteLinkLabel4MouseEntered

    private void deleteLinkLabel1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel1MouseEntered
        // TODO add your handling code here:
        if(count >= 1){
            deleteLink1.setVisible(true);
            deleteLink2.setVisible(false);
            deleteLink3.setVisible(false);
            deleteLink4.setVisible(false);
        }
    }//GEN-LAST:event_deleteLinkLabel1MouseEntered

    private void deleteLinkLabel1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel1MouseExited
        // TODO add your handling code here:
        deleteLink1.setVisible(false);
        deleteLink2.setVisible(false);
        deleteLink3.setVisible(false);
        deleteLink4.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel1MouseExited

    private void deleteLinkLabel2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel2MouseExited
        // TODO add your handling code here:
        deleteLink2.setVisible(false);
        deleteLink1.setVisible(false);
        deleteLink3.setVisible(false);
        deleteLink4.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel2MouseExited

    private void deleteLinkLabel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel3MouseExited
        // TODO add your handling code here:
        deleteLink3.setVisible(false);
        deleteLink1.setVisible(false);
        deleteLink2.setVisible(false);
        deleteLink4.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel3MouseExited

    private void deleteLinkLabel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel4MouseExited
        // TODO add your handling code here:
        deleteLink4.setVisible(false);
        deleteLink1.setVisible(false);
        deleteLink2.setVisible(false);
        deleteLink3.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel4MouseExited

    private void deleteLink1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLink1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteLink1MouseClicked

    private void deleteLink2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLink2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteLink2MouseClicked

    private void deleteLinkLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel1MouseClicked
        // TODO add your handling code here:
        quicklinksHelper helper = new quicklinksHelper();
        
        int link_id = Integer.parseInt(deleteLinkLabel1.getText());
        
        helper.deleteLink(link_id);
        
        QuickLinks window = new QuickLinks();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel1MouseClicked

    private void deleteLinkLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel2MouseClicked
        // TODO add your handling code here:
        quicklinksHelper helper = new quicklinksHelper();
        
        int link_id = Integer.parseInt(deleteLinkLabel2.getText());
        
        helper.deleteLink(link_id);
        
        QuickLinks window = new QuickLinks();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel2MouseClicked

    private void deleteLinkLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel3MouseClicked
        // TODO add your handling code here:
        quicklinksHelper helper = new quicklinksHelper();
        
        int link_id = Integer.parseInt(deleteLinkLabel3.getText());
        
        helper.deleteLink(link_id);
        
        QuickLinks window = new QuickLinks();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel3MouseClicked

    private void deleteLinkLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteLinkLabel4MouseClicked
        // TODO add your handling code here:
        quicklinksHelper helper = new quicklinksHelper();
        
        int link_id = Integer.parseInt(deleteLinkLabel4.getText());
        
        helper.deleteLink(link_id);
        
        QuickLinks window = new QuickLinks();
        window.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_deleteLinkLabel4MouseClicked

    private void dropDownActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dropDownActionPerformed
        // TODO add your handling code here:

        if (dropDown.getSelectedItem().equals("Logout")) {
            usersHelper user = new usersHelper();
            user.logout();
            this.setVisible(false);
            dispose();

            Login window = new Login();
            window.setVisible(true);
        }
    }//GEN-LAST:event_dropDownActionPerformed

    private void homeBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseEntered
        // TODO add your handling code here:
        homeUnderline.setVisible(true);
    }//GEN-LAST:event_homeBtnMouseEntered

    private void homeBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeBtnMouseExited
        // TODO add your handling code here:
        homeUnderline.setVisible(false);
    }//GEN-LAST:event_homeBtnMouseExited

    private void homeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_homeBtnActionPerformed
        // TODO add your handling code here:
        Home window = new Home();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_homeBtnActionPerformed

    private void settingsBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseClicked
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
        this.setVisible(false);
        dispose();
    }//GEN-LAST:event_settingsBtnMouseClicked

    private void settingsBtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseEntered
        // TODO add your handling code here:
        settingsUnderline.setVisible(true);
    }//GEN-LAST:event_settingsBtnMouseEntered

    private void settingsBtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsBtnMouseExited
        // TODO add your handling code here:
        settingsUnderline.setVisible(false);
    }//GEN-LAST:event_settingsBtnMouseExited

    private void settingsBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_settingsBtnActionPerformed
        // TODO add your handling code here:
        Settings window = new Settings();
        window.setVisible(true);
    }//GEN-LAST:event_settingsBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuickLinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuickLinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuickLinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuickLinks.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuickLinks().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Gmail;
    private javax.swing.JButton addLinkBtn;
    private javax.swing.JLabel addressBarError;
    private javax.swing.JButton amazon;
    private javax.swing.JLabel background;
    private javax.swing.JLabel deleteLink1;
    private javax.swing.JLabel deleteLink2;
    private javax.swing.JLabel deleteLink3;
    private javax.swing.JLabel deleteLink4;
    private javax.swing.JLabel deleteLinkLabel1;
    private javax.swing.JLabel deleteLinkLabel2;
    private javax.swing.JLabel deleteLinkLabel3;
    private javax.swing.JLabel deleteLinkLabel4;
    private javax.swing.JComboBox<String> dropDown;
    private javax.swing.JButton facebook;
    private javax.swing.JButton google;
    private javax.swing.JButton homeBtn;
    private javax.swing.JLabel homeUnderline;
    private javax.swing.JButton hotmail;
    private javax.swing.JButton link1;
    private javax.swing.JButton link2;
    private javax.swing.JButton link3;
    private javax.swing.JButton link4;
    private javax.swing.JButton openWebsite;
    private javax.swing.JButton reddit;
    private javax.swing.JButton settingsBtn;
    private javax.swing.JLabel settingsUnderline;
    private javax.swing.JButton twitter;
    private javax.swing.JTextField webInput;
    private javax.swing.JButton yahoo;
    private javax.swing.JButton youtube;
    // End of variables declaration//GEN-END:variables
}
